
package orc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HRS_GUI_GENERAL_RES_MSG.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HRS_GUI_GENERAL_RES_MSG">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CMD PERFORMED SUCCESSFULLY"/>
 *     &lt;enumeration value="CMD PERFORMED WITH PARTIAL COMPREHENSION"/>
 *     &lt;enumeration value="CMD PERFORMED, WITH MISSING INFO"/>
 *     &lt;enumeration value="CMD PERFORMED SUCCESSFULLY, BUG REQUESTED ICON COULD NOT BE DISPLAYED"/>
 *     &lt;enumeration value="PROACTIVE SIM SESSION TERMINATED BY USER"/>
 *     &lt;enumeration value="BACKWARD MOVE IN THE PROACTIVE SIM SESSION REQUESTED BY THE USER"/>
 *     &lt;enumeration value="NO RESPONSE FROM USER"/>
 *     &lt;enumeration value="HELP INFORMATION REQUIRED BY USER"/>
 *     &lt;enumeration value="ME CURRENTLY ENABLE TO PROCESS COMMAND"/>
 *     &lt;enumeration value="NETWORK CURRENTLY UNABLE TO PROCESS COMMAND"/>
 *     &lt;enumeration value="CMD BEYOND ME CAPABILITIES"/>
 *     &lt;enumeration value="CMD TYPE NOT UNDERSTOOD BY ME"/>
 *     &lt;enumeration value="CMD DATA NOT UNDERSTOOD BY ME"/>
 *     &lt;enumeration value="CMD NUMBER NOT KNOWN BY ME"/>
 *     &lt;enumeration value="SMS RPERROR"/>
 *     &lt;enumeration value="ERROR, REQUIRED VALUES ARE MISSING"/>
 *     &lt;enumeration value="INTERACTION WITH CALL CONTROL BY SIM OR MO SM CONTROL BY SIM, PERMANENT PROBLEM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HRS_GUI_GENERAL_RES_MSG")
@XmlEnum
public enum HRSGUIGENERALRESMSG {

    @XmlEnumValue("CMD PERFORMED SUCCESSFULLY")
    CMD_PERFORMED_SUCCESSFULLY("CMD PERFORMED SUCCESSFULLY"),
    @XmlEnumValue("CMD PERFORMED WITH PARTIAL COMPREHENSION")
    CMD_PERFORMED_WITH_PARTIAL_COMPREHENSION("CMD PERFORMED WITH PARTIAL COMPREHENSION"),
    @XmlEnumValue("CMD PERFORMED, WITH MISSING INFO")
    CMD_PERFORMED_WITH_MISSING_INFO("CMD PERFORMED, WITH MISSING INFO"),
    @XmlEnumValue("CMD PERFORMED SUCCESSFULLY, BUG REQUESTED ICON COULD NOT BE DISPLAYED")
    CMD_PERFORMED_SUCCESSFULLY_BUG_REQUESTED_ICON_COULD_NOT_BE_DISPLAYED("CMD PERFORMED SUCCESSFULLY, BUG REQUESTED ICON COULD NOT BE DISPLAYED"),
    @XmlEnumValue("PROACTIVE SIM SESSION TERMINATED BY USER")
    PROACTIVE_SIM_SESSION_TERMINATED_BY_USER("PROACTIVE SIM SESSION TERMINATED BY USER"),
    @XmlEnumValue("BACKWARD MOVE IN THE PROACTIVE SIM SESSION REQUESTED BY THE USER")
    BACKWARD_MOVE_IN_THE_PROACTIVE_SIM_SESSION_REQUESTED_BY_THE_USER("BACKWARD MOVE IN THE PROACTIVE SIM SESSION REQUESTED BY THE USER"),
    @XmlEnumValue("NO RESPONSE FROM USER")
    NO_RESPONSE_FROM_USER("NO RESPONSE FROM USER"),
    @XmlEnumValue("HELP INFORMATION REQUIRED BY USER")
    HELP_INFORMATION_REQUIRED_BY_USER("HELP INFORMATION REQUIRED BY USER"),
    @XmlEnumValue("ME CURRENTLY ENABLE TO PROCESS COMMAND")
    ME_CURRENTLY_ENABLE_TO_PROCESS_COMMAND("ME CURRENTLY ENABLE TO PROCESS COMMAND"),
    @XmlEnumValue("NETWORK CURRENTLY UNABLE TO PROCESS COMMAND")
    NETWORK_CURRENTLY_UNABLE_TO_PROCESS_COMMAND("NETWORK CURRENTLY UNABLE TO PROCESS COMMAND"),
    @XmlEnumValue("CMD BEYOND ME CAPABILITIES")
    CMD_BEYOND_ME_CAPABILITIES("CMD BEYOND ME CAPABILITIES"),
    @XmlEnumValue("CMD TYPE NOT UNDERSTOOD BY ME")
    CMD_TYPE_NOT_UNDERSTOOD_BY_ME("CMD TYPE NOT UNDERSTOOD BY ME"),
    @XmlEnumValue("CMD DATA NOT UNDERSTOOD BY ME")
    CMD_DATA_NOT_UNDERSTOOD_BY_ME("CMD DATA NOT UNDERSTOOD BY ME"),
    @XmlEnumValue("CMD NUMBER NOT KNOWN BY ME")
    CMD_NUMBER_NOT_KNOWN_BY_ME("CMD NUMBER NOT KNOWN BY ME"),
    @XmlEnumValue("SMS RPERROR")
    SMS_RPERROR("SMS RPERROR"),
    @XmlEnumValue("ERROR, REQUIRED VALUES ARE MISSING")
    ERROR_REQUIRED_VALUES_ARE_MISSING("ERROR, REQUIRED VALUES ARE MISSING"),
    @XmlEnumValue("INTERACTION WITH CALL CONTROL BY SIM OR MO SM CONTROL BY SIM, PERMANENT PROBLEM")
    INTERACTION_WITH_CALL_CONTROL_BY_SIM_OR_MO_SM_CONTROL_BY_SIM_PERMANENT_PROBLEM("INTERACTION WITH CALL CONTROL BY SIM OR MO SM CONTROL BY SIM, PERMANENT PROBLEM");
    private final String value;

    HRSGUIGENERALRESMSG(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HRSGUIGENERALRESMSG fromValue(String v) {
        for (HRSGUIGENERALRESMSG c: HRSGUIGENERALRESMSG.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
