
package orc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ORC", targetNamespace = "ORC", wsdlLocation = "file:/WorkSpace/Products/ASA_/Modulos/Server/Orchestrator/API/src/conf/xml-resources/web-services/SONotif/wsdl/VIVONotif.wsdl")
public class ORC
    extends Service
{

    private final static URL ORC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(orc.ORC.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = orc.ORC.class.getResource(".");
            url = new URL(baseUrl, "file:/WorkSpace/Products/ASA_/Modulos/Server/Orchestrator/API/src/conf/xml-resources/web-services/SONotif/wsdl/VIVONotif.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/WorkSpace/Products/ASA_/Modulos/Server/Orchestrator/API/src/conf/xml-resources/web-services/SONotif/wsdl/VIVONotif.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORC_WSDL_LOCATION = url;
    }

    public ORC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ORC() {
        super(ORC_WSDL_LOCATION, new QName("ORC", "ORC"));
    }

    /**
     * 
     * @return
     *     returns ORCPortType
     */
    @WebEndpoint(name = "ORCPort")
    public ORCPortType getORCPort() {
        return super.getPort(new QName("ORC", "ORCPort"), ORCPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ORCPortType
     */
    @WebEndpoint(name = "ORCPort")
    public ORCPortType getORCPort(WebServiceFeature... features) {
        return super.getPort(new QName("ORC", "ORCPort"), ORCPortType.class, features);
    }

}
