
package orc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ORCPortType", targetNamespace = "ORC")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ORCPortType {


    /**
     * Service definition of function ORC__AsyncACK
     * 
     * @param porData
     * @param message
     * @param transactionId
     * @param msisdn
     * @param smmId
     * @param deliveryStatus
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AsyncACK", action = "Async#ACK")
    @WebResult(name = "result", partName = "result")
    public int asyncACK(
        @WebParam(name = "smmId", partName = "smmId")
        int smmId,
        @WebParam(name = "msisdn", partName = "msisdn")
        String msisdn,
        @WebParam(name = "transactionId", partName = "transactionId")
        int transactionId,
        @WebParam(name = "deliveryStatus", partName = "deliveryStatus")
        REQSTATUS deliveryStatus,
        @WebParam(name = "message", partName = "message")
        String message,
        @WebParam(name = "porData", partName = "porData")
        String porData);

    /**
     * Service definition of function ORC__InitialSMS
     * 
     * @param imei
     * @param msisdnFake
     * @param loci
     * @param smmId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "InitialSMS", action = "Initial#SMS")
    @WebResult(name = "result", partName = "result")
    public int initialSMS(
        @WebParam(name = "smmId", partName = "smmId")
        int smmId,
        @WebParam(name = "msisdnFake", partName = "msisdnFake")
        String msisdnFake,
        @WebParam(name = "imei", partName = "imei")
        String imei,
        @WebParam(name = "loci", partName = "loci")
        String loci);

    /**
     * Service definition of function ORC__InteractUserAnswer
     * 
     * @param generalResultCode
     * @param generalResultMsg
     * @param transactionId
     * @param choice
     * @param msisdnFake
     * @param cmdType
     * @param smmId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "InteractUserAnswer", action = "Interact#UserAnswer")
    @WebResult(name = "result", partName = "result")
    public int interactUserAnswer(
        @WebParam(name = "smmId", partName = "smmId")
        int smmId,
        @WebParam(name = "msisdnFake", partName = "msisdnFake")
        String msisdnFake,
        @WebParam(name = "transactionId", partName = "transactionId")
        int transactionId,
        @WebParam(name = "cmdType", partName = "cmdType")
        HRSGUICMDTYPE cmdType,
        @WebParam(name = "generalResultCode", partName = "generalResultCode")
        int generalResultCode,
        @WebParam(name = "generalResultMsg", partName = "generalResultMsg")
        HRSGUIGENERALRESMSG generalResultMsg,
        @WebParam(name = "choice", partName = "choice")
        HRSGUICHOICE choice);

    /**
     * Service definition of function ORC__ActivationAnswer
     * 
     * @param transactionId
     * @param iccid
     * @param smmId
     * @param msisdnReal
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ActivationAnswer", action = "Activation#Answer")
    @WebResult(name = "result", partName = "result")
    public int activationAnswer(
        @WebParam(name = "smmId", partName = "smmId")
        int smmId,
        @WebParam(name = "msisdnReal", partName = "msisdnReal")
        String msisdnReal,
        @WebParam(name = "transactionId", partName = "transactionId")
        int transactionId,
        @WebParam(name = "iccid", partName = "iccid")
        String iccid);

}
